# Default configurations for tracking and video generation
default_detector: 'saves/pretrained/e31_detector.pt'
default_tracker: 'cfg/trackers/tuning/exp31/best_tracker.yaml'
default_drone_profile: 'dji_phantom_4_pro_v2' # The default drone profile to use. Configurations located in drone_profile_dir
default_video_resize_ratio: 0.25
estimated_drone_starting_altitude_m: 2.25 # meters
drone_sensor_height_mm: 8 # millimeters

# File system organization
storage_root: '..' # Intended for large data, not code. Either absolute, or relative to the project root.
amp_check_models_dir: 'saves/pretrained' # Subdirectory of storage_root
drone_profile_dir: 'cfg/drones' # Subdirectory of project root
user_settings_dir: 'usr' # Subdirectory of project root
images_dir: 'images' # Subdirectory of all dataset directories
labels_dir: 'labels' # Subdirectory of all dataset directories
tracks_dir: 'tracks' # Subdirectory of all dataset directories
dataset_split_dirs: # Subdirectories of some datasets -- only used for searching and not for saving
  - 'train'
  - 'val'
  - 'valid'
  - 'test'

# Output file names
args_file: 'args.yaml' # Arguments file for track_from_video.py
evaluation_results_file: 'evaluation_results.txt' # For eval.py
evolution_log_file: 'evolutions.yaml'

# Tracking results files (all of these will have the run name prepended)
gt_file_suffix: 'gt_formatted.txt'
results_file_suffix: 'results.txt'
metrics_file_suffix: 'mot_evaluation.csv'
metrics_events_suffix: 'mot_events.csv'
researcher_output_suffix: 'output.csv'
prediction_video_suffix: 'predictions.mp4'
gt_video_suffix: 'gt.mp4'

# Default tracking configuration files
ultralytics_bytetrack: 'cfg/trackers/bytetrack_default.yaml' # Relative to project root
ultralytics_botsort: 'cfg/trackers/botsort_default.yaml' # Relative to project root

# Files for internal use
tracking_hyp_file: 'tracking_hyperparameters.yaml'
checkpoint_file: 'checkpoint.yaml'
user_settings_file: 'user_settings.yaml'

# Dataset conversion settings (the class names, coming out of labelme, that have been observed as valid dolphins)
dolphin_classes:
  - Dolphin
  - dolphin
  - box
  - rectangle

tracking_metrics:
  - mota
  - motp
  - idf1
  - num_objects
  - num_false_positives
  - num_misses
  - num_switches
  - num_fragmentations
  - num_matches
  - num_frames
  - idfp
  - idfn
  - idtp
  - mostly_tracked
  - partially_tracked
  - mostly_lost

tracking_metrics_names:
  hota_alpha: 'HOTA'
  assa_alpha: 'ASSA'
  deta_alpha: 'DETA'
  num_frames: 'Frames'
  idf1: 'ID_F1'
  idp: 'ID_Precision'
  idr: 'ID_Recall'
  recall: 'Recall'
  precision: 'Precision'
  num_objects: 'Objects'
  mostly_tracked: 'Mostly_Track'
  partially_tracked: 'Part_Track'
  mostly_lost: 'Mostly_Lost'
  num_false_positives: 'False_Pos'
  num_misses: 'Misses'
  num_switches: 'Switches'
  num_fragmentations: 'Fragmt.'
  mota: 'MOTA'
  motp: 'MOTP'
  id_global_assignment: 'ID_Global_Assn'
  obj_frequencies: 'Object_Freq'
  num_unique_objects: 'Num_Unique_Objects'
  idfp: 'ID_False_Pos'
  idfn: 'ID_False_Neg'
  idtp: 'ID_True_Pos'
  num_matches: 'Num_Matches'



