# File System Organization
data_config_dir: 'cfg/data'
runs_dir: '../runs/'
amp_check_models_dir: '../saves/pretrained'
pretrained_models_dir: '../saves/pretrained'
hyp_config_dir: 'cfg/hyp'

# Custom settings
tracker_empty_frames_reset: 25

# Tracking results files
gt_file_suffix: 'gt_formatted.txt'
results_file_suffix: 'results.txt'
metrics_file_suffix: 'mot_evaluation.csv'
metrics_events_suffix: 'mot_events.csv'
researcher_output_suffix: 'output.csv'

ultralytics_bytetrack: 'dolphin_tracker/cfg/trackers/bytetrack_default.yaml'
ultralytics_botsort: 'dolphin_tracker/cfg/trackers/botsort_default.yaml'

tracking_metrics:
  - mota
  - motp
  - idf1
  - num_objects
  - num_false_positives
  - num_misses
  - num_switches
  - num_fragmentations
  - num_frames
  - idfp
  - idfn
  - idtp
  - num_matches
  - mostly_tracked
  - partially_tracked
  - mostly_lost