# Default configurations for tracking and video generation
default_detector: 'saves/pretrained/e57_detector.pt' # Relative to storage_root
default_orientation_model: 'saves/orientations/e61_best.pth' # Relative to storage_root
default_tracker: 'cfg/trackers/tuning/exp60/e60_best.yaml' # Relative to project root
default_drone_profile: 'dji_phantom_4_pro_v2' # The default drone profile to use. Configurations located in drone_profile_dir
default_video_resize_ratio: 0.25
estimated_drone_starting_altitude_m: 2.25 # meters
drone_sensor_height_mm: 8 # millimeters

# File system organization
storage_root: '..' # Intended for large data, not code. Either absolute, or relative to the project root.
amp_check_models_dir: 'saves/pretrained' # Subdirectory of storage_root
drone_profile_dir: 'cfg/drones' # Subdirectory of project root
user_settings_dir: 'usr' # Subdirectory of project root
detector_runs_dir: 'runs' # Subdirectory of storage root
logs_dir: 'logs' # Subdirectory of storage root
data_dir: 'data' # Subdirectory of storage root
output_dir: 'output' # Subdirectory of storage root
tracker_output_dir: 'tracker' # Subdirectory of output_dir
extracted_frames_dir: 'extracted' # Subdirectory of data_dir
log_results_dir: 'results' # Subdirectory of logs_dir
log_slurm_dir: 'slurm' # Subdirectory of logs_dir
training_log_prefix: 'train' # Prefix for training log files
training_runs_dir: 'train/stage1' # Subdirectory of detector_runs_dir
images_dir: 'images' # Subdirectory of all dataset directories
labels_dir: 'labels' # Subdirectory of all dataset directories
orientations_dir: 'orientations' # Subdirectory of dataset directories which have orientations
tracks_dir: 'tracks' # Subdirectory of all dataset directories
orientations_library_dir: 'cropped_images'
dataset_split_dirs: # Subdirectories of some datasets -- only used for searching and not for saving
  - 'train'
  - 'val'
  - 'valid'
  - 'test'
dataset_train_split: 'train' # Subdirectory of the dataset root
dataset_valid_split: 'valid' # Subdirectory of the dataset root
dataset_test_split: 'test' # Subdirectory of the dataset root

# Output file names
args_file: 'args.yaml' # Arguments file for track_from_video.py
evaluation_results_file: 'evaluation_results.txt' # For eval.py
prediction_results_file: 'predictions.txt' # For predict.py
evolution_log_file: 'evolutions.yaml'
orientations_weights_file: 'orientations_weights.pth'

# Training results files
training_results_csv: 'results.csv'

# Tracking results files (all of these will have the run name prepended)
gt_file_suffix: 'gt_formatted.txt'
results_file_suffix: 'results.txt'
metrics_file_suffix: 'mot_evaluation.csv'
metrics_events_suffix: 'mot_events.csv'
researcher_output_suffix: 'output.csv'
prediction_video_suffix: 'predictions.mp4'
gt_video_suffix: 'gt.mp4'
images_index_suffix: 'images_index.txt'
orientations_results_suffix: 'orientations.txt'
gt_images_index_suffix: 'gt_images_index.txt'
orientations_metrics_suffix: 'orientation_metrics.csv'
orientations_line_results_suffix: 'orientation_evaluation_lines.csv'
hota_file_suffix: 'trackeval.txt'

# Default tracking configuration files
ultralytics_bytetrack: 'cfg/trackers/bytetrack_default.yaml' # Relative to project root
ultralytics_botsort: 'cfg/trackers/botsort_default.yaml' # Relative to project root

# Files for internal use
tracking_hyp_file: 'tracking_hyperparameters.yaml'
checkpoint_file: 'checkpoint.yaml'
user_settings_file: 'user_settings.yaml'

# Video generation settings
track_colors:
  - [255, 0, 0]
  - [0, 255, 0]
  - [255, 255, 0]
  - [255, 0, 255]
  - [128, 0, 128]
  - [128, 128, 0]
  - [128, 0, 0]
  - [0, 128, 0]

# Dataset conversion settings (the class names, coming out of labelme, that have been observed as valid dolphins)
dolphin_classes:
  - Dolphin
  - dolphin
  - box
  - rectangle
  - box2

head_classes:
  - Head
  - snout
  - head

tail_classes:
  - Tail
  - tail

# File columns
bbox_file_columns:
    - 'frame'
    - 'id'
    - 'x'
    - 'y'
    - 'w'
    - 'h'
    - 'score'
    - 'class'
    - 'visibility'

obb_file_columns:
    - 'frame'
    - 'id'
    - 'x1'
    - 'y1'
    - 'x2'
    - 'y2'
    - 'x3'
    - 'y3'
    - 'x4'
    - 'y4'
    - 'score'
    - 'class'
    - 'visibility'

orientation_file_columns:
    - 'label_index'
    - 'x'
    - 'y'

orientation_results_file_columns:
  - 'angle'
  - 'x_val'
  - 'y_val'
  - 'dataloader_index'
  - 'filename'
  - 'object_id'

# Image file settings
image_file_extensions: # Note that currently jpg is the only fully supported format, but this is for future expansion
  - '.jpg'
  - '.jpeg'
  - '.png'

frame_number_regex: '_(\d+)\.' # Regular expression to extract the frame number from the image file name

# Metrics sets
training_metrics_to_print:
  - 'metrics/precision(B)'
  - 'metrics/recall(B)'
  - 'metrics/mAP50(B)'
  - 'metrics/mAP50-95(B)'
  - 'val/box_loss'
  - 'val/cls_loss'
  - 'val/dfl_loss'

tracking_metrics:
  - mota
  - motp
  - idf1
  - num_objects
  - num_false_positives
  - num_misses
  - num_switches
  - num_fragmentations
  - num_matches
  - num_frames
  - idfp
  - idfn
  - idtp
  - mostly_tracked
  - partially_tracked
  - mostly_lost

tracking_metrics_names:
  hota_alpha: 'HOTA'
  assa_alpha: 'ASSA'
  deta_alpha: 'DETA'
  num_frames: 'Frames'
  idf1: 'ID_F1'
  idp: 'ID_Precision'
  idr: 'ID_Recall'
  recall: 'Recall'
  precision: 'Precision'
  num_objects: 'Objects'
  mostly_tracked: 'Mostly_Track'
  partially_tracked: 'Part_Track'
  mostly_lost: 'Mostly_Lost'
  num_false_positives: 'False_Pos'
  num_misses: 'Misses'
  num_switches: 'Switches'
  num_fragmentations: 'Fragmt.'
  mota: 'MOTA'
  motp: 'MOTP'
  id_global_assignment: 'ID_Global_Assn'
  obj_frequencies: 'Object_Freq'
  num_unique_objects: 'Num_Unique_Objects'
  idfp: 'ID_False_Pos'
  idfn: 'ID_False_Neg'
  idtp: 'ID_True_Pos'
  num_matches: 'Num_Matches'



