common: &common_settings
  img_size: 640
  batch_size: 16
  task: 'detect'

train:
  <<: *common_settings
  hyp: 'cfg/hyp/yolo11m_toy.yaml'
  pretrained_model: '../saves/pretrained/yolo11m.pt'

val:
  <<: *common_settings

test:
  <<: *common_settings